import { Database } from "bun:sqlite";
import { SQL } from "bun";
import { createHash } from "node:crypto";
import { assertPostgresUrl } from "./databaseConfig";

const COPY_BATCH_SIZE = 500;
const INTERNAL_SQLITE_TABLE = /^sqlite_/;

export interface DatabaseMigrationProgress {
  phase: "schema" | "data" | "constraints" | "validation" | "complete";
  table?: string;
  copiedRows: number;
  totalRows: number;
}

export interface DatabaseMigrationResult {
  receiptId: string;
  tables: number;
  rows: number;
  counts: Record<string, number>;
  keyChecksums: Record<string, string>;
}

interface SQLiteTableDefinition {
  name: string;
  sql: string;
}

function quoteIdentifier(value: string): string {
  return `"${value.replaceAll('"', '""')}"`;
}

function quoteLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

const ON_ACTION =
  "(?:\\s+ON\\s+DELETE\\s+(?:CASCADE|RESTRICT|SET\\s+NULL|SET\\s+DEFAULT|NO\\s+ACTION))?(?:\\s+ON\\s+UPDATE\\s+(?:CASCADE|RESTRICT|SET\\s+NULL|SET\\s+DEFAULT|NO\\s+ACTION))?";

function stripInlineForeignKeys(sql: string): string {
  // Drop table-level FOREIGN KEY (...) REFERENCES ... first. Leaving a bare
  // FOREIGN KEY (...) after stripping only the REFERENCES clause is invalid
  // PostgreSQL (seen on followed_playlist_download_protections).
  return sql
    .replace(
      new RegExp(
        `,?\\s*FOREIGN\\s+KEY\\s*\\([^)]*\\)\\s*REFERENCES\\s+(?:"[^"]+"|[A-Za-z_][\\w]*)\\s*\\([^)]*\\)${ON_ACTION}`,
        "gi",
      ),
      "",
    )
    .replace(
      new RegExp(
        `\\s+REFERENCES\\s+(?:"[^"]+"|[A-Za-z_][\\w]*)\\s*\\([^)]*\\)${ON_ACTION}`,
        "gi",
      ),
      "",
    );
}

/** Translate the deliberately conservative subset used by YT Zero's schema. */
export function sqliteCreateTableToPostgres(sql: string): string {
  return stripInlineForeignKeys(sql)
    .replace(/^CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?/i, "CREATE TABLE ")
    .replace(/INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/\s+AUTOINCREMENT\b/gi, "")
    .replace(/\s+COLLATE\s+NOCASE\b/gi, "")
    .replace(/\bBLOB\b/gi, "BYTEA")
    .replace(/\bREAL\b/gi, "DOUBLE PRECISION")
    .replace(
      /DEFAULT\s*\(datetime\('now'\)\)/gi,
      "DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')",
    )
    .replace(/DEFAULT\s*\(date\('now',\s*'localtime'\)\)/gi, "DEFAULT (CURRENT_DATE::text)")
    .replace(
      /DEFAULT\s*\(CAST\(strftime\('%H',\s*'now'(?:,\s*'localtime')?\)\s+AS\s+INTEGER\)\)/gi,
      "DEFAULT (EXTRACT(HOUR FROM LOCALTIME)::INTEGER)",
    )
    // SQLite INTEGER is a signed 64-bit storage class. PostgreSQL INTEGER is
    // only 32-bit, which is too small for millisecond timestamps and byte sizes.
    .replace(/\bINTEGER\b/gi, "BIGINT");
}

export function sqliteCreateIndexToPostgres(sql: string): string {
  return sql
    .replace(/^CREATE\s+(UNIQUE\s+)?INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?/i, (_match, unique) => `CREATE ${unique ?? ""}INDEX `)
    .replace(/\s+COLLATE\s+NOCASE\b/gi, "");
}

function sqliteTables(source: Database): SQLiteTableDefinition[] {
  return (source.query(
    "SELECT name, sql FROM sqlite_master WHERE type='table' AND sql IS NOT NULL ORDER BY name",
  ).all() as SQLiteTableDefinition[]).filter((table) => !INTERNAL_SQLITE_TABLE.test(table.name));
}

function sqliteIndexes(source: Database): string[] {
  return (source.query(
    "SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL ORDER BY name",
  ).all() as { sql: string }[]).map((row) => row.sql);
}

function tableColumns(source: Database, table: string): { name: string; pk: number }[] {
  return source.query(`PRAGMA table_info(${quoteIdentifier(table)})`).all() as { name: string; pk: number }[];
}

function foreignKeys(source: Database, table: string): { id: number; seq: number; table: string; from: string; to: string; on_update: string; on_delete: string }[] {
  return source.query(`PRAGMA foreign_key_list(${quoteIdentifier(table)})`).all() as any[];
}

function postgresAction(action: string): string {
  const normalized = action.toUpperCase();
  return ["CASCADE", "RESTRICT", "SET NULL", "SET DEFAULT", "NO ACTION"].includes(normalized) ? normalized : "NO ACTION";
}

async function clearPrematureImageCache(target: SQL): Promise<void> {
  // imgcache.ts historically created this table during module load. If that races
  // ahead of migration, the only public table is an empty image_cache leftover.
  const rows = await target.unsafe<{ name: string }[]>(
    "SELECT table_name AS name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE' ORDER BY name",
  );
  if (rows.length === 1 && rows[0].name === "image_cache") {
    await target.unsafe("DROP TABLE image_cache");
  }
}

async function targetMustBeEmpty(target: SQL): Promise<void> {
  await clearPrematureImageCache(target);
  const rows = await target.unsafe<{ name: string }[]>(
    "SELECT table_name AS name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE' LIMIT 1",
  );
  if (rows.length) throw new Error(`target PostgreSQL database is not empty (found table ${rows[0].name})`);
}

async function copyTable(source: Database, target: SQL, table: string): Promise<number> {
  const columns = tableColumns(source, table).map((column) => column.name);
  if (columns.length === 0) return 0;
  const quotedTable = quoteIdentifier(table);
  const quotedColumns = columns.map(quoteIdentifier).join(", ");
  const total = Number((source.query(`SELECT COUNT(*) AS count FROM ${quotedTable}`).get() as any).count);

  for (let offset = 0; offset < total; offset += COPY_BATCH_SIZE) {
    const rows = source.query(`SELECT ${quotedColumns} FROM ${quotedTable} LIMIT ? OFFSET ?`).all(COPY_BATCH_SIZE, offset) as Record<string, unknown>[];
    if (rows.length === 0) break;
    const values: unknown[] = [];
    const tuples = rows.map((row) => `(${columns.map((column) => {
      values.push(row[column]);
      return `$${values.length}`;
    }).join(", ")})`);
    await target.unsafe(`INSERT INTO ${quotedTable} (${quotedColumns}) VALUES ${tuples.join(", ")}`, values);
  }
  return total;
}

async function resetIdentity(source: Database, target: SQL, table: string): Promise<void> {
  const sql = (source.query("SELECT sql FROM sqlite_master WHERE type='table' AND name=?").get(table) as any)?.sql as string | undefined;
  if (!sql || !/AUTOINCREMENT/i.test(sql)) return;
  const pk = tableColumns(source, table).find((column) => column.pk === 1);
  if (!pk) return;
  const relation = quoteLiteral(table);
  const column = quoteLiteral(pk.name);
  await target.unsafe(
    `SELECT setval(pg_get_serial_sequence(${relation}, ${column}), COALESCE(MAX(${quoteIdentifier(pk.name)}), 1), COUNT(*) > 0) FROM ${quoteIdentifier(table)}`,
  );
}

function hashKeyRows(rows: Record<string, unknown>[], columns: string[]): string {
  const hash = createHash("sha256");
  for (const row of rows) {
    for (const column of columns) {
      const value = row[column];
      hash.update(value === null ? "-1:" : `${String(value).length}:${String(value)}`);
      hash.update("|");
    }
    hash.update("\n");
  }
  return hash.digest("hex");
}

async function validatePrimaryKeyChecksum(source: Database, target: SQL, table: string): Promise<string | null> {
  const primaryKey = tableColumns(source, table)
    .filter((column) => column.pk > 0)
    .sort((a, b) => a.pk - b.pk)
    .map((column) => column.name);
  if (primaryKey.length === 0) return null;
  const projection = primaryKey.map(quoteIdentifier).join(", ");
  const order = primaryKey.map(quoteIdentifier).join(", ");
  const sourceRows = source.query(`SELECT ${projection} FROM ${quoteIdentifier(table)} ORDER BY ${order}`).all() as Record<string, unknown>[];
  const targetRows = await target.unsafe<Record<string, unknown>[]>(`SELECT ${projection} FROM ${quoteIdentifier(table)} ORDER BY ${order}`);
  const sourceHash = hashKeyRows(sourceRows, primaryKey);
  const targetHash = hashKeyRows(targetRows, primaryKey);
  if (sourceHash !== targetHash) throw new Error(`primary-key checksum validation failed for ${table}`);
  return sourceHash;
}

async function addForeignKeys(source: Database, target: SQL, tables: SQLiteTableDefinition[]): Promise<void> {
  for (const table of tables) {
    const grouped = new Map<number, ReturnType<typeof foreignKeys>>();
    for (const fk of foreignKeys(source, table.name)) {
      const rows = grouped.get(fk.id) ?? [];
      rows.push(fk);
      grouped.set(fk.id, rows);
    }
    for (const [id, cols] of grouped) {
      cols.sort((a, b) => a.seq - b.seq);
      const head = cols[0];
      const fromCols = cols.map((col) => quoteIdentifier(col.from)).join(", ");
      const toCols = cols.map((col) => quoteIdentifier(col.to)).join(", ");
      const constraint = `fk_${table.name}_${id}_${cols.map((col) => col.from).join("_")}`.slice(0, 63);
      await target.unsafe(
        `ALTER TABLE ${quoteIdentifier(table.name)} ADD CONSTRAINT ${quoteIdentifier(constraint)} FOREIGN KEY (${fromCols}) REFERENCES ${quoteIdentifier(head.table)} (${toCols}) ON UPDATE ${postgresAction(head.on_update)} ON DELETE ${postgresAction(head.on_delete)} NOT VALID`,
      );
      await target.unsafe(`ALTER TABLE ${quoteIdentifier(table.name)} VALIDATE CONSTRAINT ${quoteIdentifier(constraint)}`);
    }
  }
}

export async function migrateSQLiteToPostgres(
  sourcePath: string,
  targetUrl: string,
  onProgress: (progress: DatabaseMigrationProgress) => void = () => {},
): Promise<DatabaseMigrationResult> {
  assertPostgresUrl(targetUrl);
  const source = new Database(sourcePath, { readonly: true });
  const target = new SQL(targetUrl, { max: 1 });
  const receiptId = crypto.randomUUID();
  const counts: Record<string, number> = {};
  const keyChecksums: Record<string, string> = {};

  try {
    source.exec("PRAGMA foreign_keys=ON; BEGIN;");
    await targetMustBeEmpty(target);
    const tables = sqliteTables(source);
    const totalRows = tables.reduce((sum, table) => sum + Number((source.query(`SELECT COUNT(*) AS count FROM ${quoteIdentifier(table.name)}`).get() as any).count), 0);
    let copiedRows = 0;

    await target.begin(async (tx) => {
      onProgress({ phase: "schema", copiedRows, totalRows });
      for (const table of tables) await tx.unsafe(sqliteCreateTableToPostgres(table.sql));
      for (const index of sqliteIndexes(source)) await tx.unsafe(sqliteCreateIndexToPostgres(index));
      await tx.unsafe("CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_user_name_nocase ON tags(user_id, lower(name))");

      for (const table of tables) {
        onProgress({ phase: "data", table: table.name, copiedRows, totalRows });
        counts[table.name] = await copyTable(source, tx, table.name);
        copiedRows += counts[table.name];
        await resetIdentity(source, tx, table.name);
      }

      onProgress({ phase: "constraints", copiedRows, totalRows });
      await addForeignKeys(source, tx, tables);
      await tx.unsafe(`
        CREATE TABLE database_migration_receipts (
          id TEXT PRIMARY KEY,
          source_engine TEXT NOT NULL,
          target_engine TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          table_counts JSONB NOT NULL,
          key_checksums JSONB NOT NULL
        )
      `);
      onProgress({ phase: "validation", copiedRows, totalRows });
      for (const table of tables) {
        const row = await tx.unsafe<{ count: number }[]>(`SELECT COUNT(*)::integer AS count FROM ${quoteIdentifier(table.name)}`);
        if (Number(row[0]?.count ?? -1) !== counts[table.name]) throw new Error(`row-count validation failed for ${table.name}`);
        const checksum = await validatePrimaryKeyChecksum(source, tx, table.name);
        if (checksum) keyChecksums[table.name] = checksum;
      }
      await tx.unsafe(
        "INSERT INTO database_migration_receipts (id, source_engine, target_engine, table_counts, key_checksums) VALUES ($1, 'sqlite', 'postgres', $2::jsonb, $3::jsonb)",
        [receiptId, JSON.stringify(counts), JSON.stringify(keyChecksums)],
      );
    });

    source.exec("COMMIT;");
    onProgress({ phase: "complete", copiedRows, totalRows });
    return { receiptId, tables: Object.keys(counts).length, rows: copiedRows, counts, keyChecksums };
  } catch (error) {
    try { source.exec("ROLLBACK;"); } catch {}
    throw error;
  } finally {
    source.close();
    await target.close();
  }
}
